# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: delete certificate from node
  file:
    path: "{{ docker_registry_ip }}:{{ docker_registry_port }}"
    state: absent
  ignore_errors: yes
