# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: create directory for copying certificate
  file:
    path: /etc/docker/certs.d/{{ harbor_registry_ip }}:{{ harbor_registry_port }}
    state: directory

- name: get ca.crt from registry
  shell: set -o pipefail && echo -n | openssl s_client -showcerts -connect {{ harbor_registry_ip }}:{{ harbor_registry_port }} 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > harbor.crt
  args:
    chdir: "/etc/docker/certs.d/{{ harbor_registry_ip }}:{{ harbor_registry_port }}"

- name: login harbor registry firstly
  shell: docker login {{ harbor_registry_ip }}:{{ harbor_registry_port }} -uadmin -p{{ harborAdminPassword }}
  register: result
  until: result is succeeded
  retries: 60
  delay: 10
  ignore_errors: yes
