apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nginxcdn.fullname" . }}-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
        app.kubernetes.io/name: {{ template "nginxcdn.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 192.168.1.0/24
    ports:
    {{- if kindIs "map" .Values.nginx.http.server }}
    - protocol: TCP
      port: {{ default 80 .Values.nginx.http.server.port }}
    - protocol: TCP
      port: {{ default 443 .Values.nginx.http.server.sslport }}
    {{- else }}
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
    {{- end }}
