# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-vas-cons-app
  namespace: default
  labels:
    name: {{ .Release.Name }}-vas-cons-app
spec:
  containers:
  - name: {{ .Release.Name }}-vas-cons-app
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.pullPolicy }}
    volumeMounts:
        - name: tmp
          mountPath: /tmp

  volumes:
      - name: tmp
        hostPath:
            path: /tmp
