# Copyright (c) 2022 Nokia Corporation
# Licensed under the Apache License 2.0
# SPDX-License-Identifier: Apache-2.0
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: enc-nwi-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - nwi.enc.nokia.com
  resources:
  - srlinuxconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nwi.enc.nokia.com
  resources:
  - srlinuxconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - nwi.enc.nokia.com
  resources:
  - srlinuxconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nwi.enc.nokia.com
  resources:
  - srosconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nwi.enc.nokia.com
  resources:
  - srosconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - nwi.enc.nokia.com
  resources:
  - srosconfigs/status
  verbs:
  - get
  - patch
  - update
