
{{- if .Values.simulatorService.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.simulatorService.name}}
spec:
  type: NodePort
  ports:
  {{- range .Values.simulatorService.ports }}
  - name: {{ .name }}
    targetPort: {{ .targetPort}}
    port: {{ .port}}
    nodePort: {{.nodePort}}
  {{- end }}
  selector:
    run: location-api 
{{- end}}