# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---
apiVersion: v1
kind: Pod
metadata:
  name: vas-cons-app
  namespace: default
  labels:
    name: vas-cons-app
spec:
  containers:
  - name: vas-cons-app
    image: vas-cons-app:1.0
    imagePullPolicy: Never
    volumeMounts:
        - name: tmp
          mountPath: /tmp

  volumes:
      - name: tmp
        hostPath:
            path: /tmp
