# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

docker_name: "ia_visualizer"
docker_image: "{{ docker_registry_address }}/{{ docker_name }}:{{ eis_version }}"
camera_stream_results_port: 65013
app_name: "Visualizer"
peer: "client"
cert_name: "etcd_{{ app_name }}_cert"
key_name: "etcd_{{ app_name }}_key"
publisher_pod_service: "ia-video-analytics-service"
helm_release_name: "visualizer-release"
helm_chart_visualizer: "{{ helm_charts_location }}/visualizer"
