# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: delete etcd pod
  command: kubectl -n eis delete pod ia-etcd
  changed_when: true
  ignore_errors: yes

- name: delete namespace
  command: kubectl delete namespace eis
  changed_when: true
  ignore_errors: yes

