# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

apiVersion: v2
name: upf
description: A Helm chart for VPP based   UPF deployment

type: application

version: 0.1.0

appVersion: 0.1.0
