# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 LINKS Foundation
apiVersion: v1
kind: Pod
metadata: 
    name: consumer
    labels:
      locationService: active
spec: 
    containers: 
    - 
        image: "location-consumer-test:latest"
        imagePullPolicy: Never
        name: consumer
        ports:
            - containerPort: 8082
            
        
