# Copyright (c) 2022 Nokia Corporation
# Licensed under the Apache License 2.0
# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
appVersion: 22.6-20220629112148
description: A Helm chart for deploying NwI Operator
name: enc-nwi-operator
type: application
version: 22.6-20220629112148
