NAME: upf-app
LAST DEPLOYED: Mon Jun  8 22:42:14 2020
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
image:
  repository: upf-app
node:
  name: esi13
  path: /root/astri/upf

COMPUTED VALUES:
allowPrivilegeEscalation: true
hugePageAmount: 4Gi
hugePageSize: hugepages-1Gi
image:
  pullPolicy: IfNotPresent
  repository: upf-app
  tag: "1.0"
isPrivileged: true
memory: 6Gi
node:
  name: esi13
  path: /root/astri/upf
restartPolicy: Never
upf:
  huge_memory: 4G
  main_core: 1
  n3_addr: 192.179.120.170/24
  n4_addr: 192.179.120.170/24
  n6_addr: 192.179.120.170/24
  n6_gw_addr: 192.168.1.170
  pci_bus_addr: af:0a.0
  pfcp_thread:
    cores: 4
    count: 1
  uio_driver: igb_uio
  vf_if_name: VirtualFunctionEthernet
  worker_cores: 2,3

HOOKS:
MANIFEST:
---
# Source: upf/templates/5g-upf.yaml
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

#name: upf-cpp
apiVersion: v1
kind: Pod
metadata:
  name: upf-app
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-openness
spec:
  nodeName: esi13
  containers:
    - name: upf-app
      image: "upf-app:1.0"
      securityContext:
        allowPrivilegeEscalation: true
        privileged: true
      command: ["/bin/bash", "-c", "--"]
      args:
      - |
        while true ; do
          sleep 90000000
        done
      imagePullPolicy: IfNotPresent
      env:
        - name: CONFIG_VF_IF_NAME
          value: VirtualFunctionEthernet
        - name: CONFIG_PCI_BUS_ADDR
          value: af:0a.0
        - name: CONFIG_PCI_POLL_DRIVER_TYPE
          value: igb_uio
        - name: CONFIG_HUGE_MEMORY
          value: 4G
        - name: CONFIG_MAIN_CORE
          value: 1
        - name: CONFIG_WORKER_CORES
          value: 2,3
        - name: CONFIG_PFCP_THREAD_CORES
          value: 4
        - name: CONFIG_NO_OF_PFCP_THREADS
          value: 1
        - name: CONFIG_N3_IP_ADDR
          value: 192.179.120.170/24
        - name: CONFIG_N4_IP_ADDR
          value: 192.179.120.170/24
        - name: CONFIG_N6_IP_ADDR
          value: 192.179.120.170/24
        - name: CONFIG_N6_GW_IP_ADDR
          value: 192.168.1.170
      volumeMounts:
        - name: hugepages
          mountPath: /hugepages
        - name: class
          mountPath: /sys/devices
          readOnly: false
        - name: upf-vol
          mountPath: /root/upf
          readOnly: false
        - name: sysfs
          mountPath: /sys
          readOnly: false
        - name: host-proc
          mountPath: /host/proc
        - name: varvol
          mountPath: /var/run
          readOnly: false
      resources:
        requests:
          hugepages-1Gi : 4Gi
          memory: 6Gi
          intel.com/intel_sriov_dpdk: "1"
        limits:
          hugepages-1Gi : 4Gi
          memory: 6Gi
          intel.com/intel_sriov_dpdk: "1"
  volumes:
  - name: hugepages
    emptyDir:
      medium: HugePages
  - name: class
    hostPath:
      path: /sys/devices
  - name: sysfs
    hostPath:
        path: /sys
  - name: upf-vol
    hostPath:
      path: /root/astri/upf
  - name: host-proc
    hostPath:
        path: /proc
  - name: varvol
    hostPath:
        path: /var/run

  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"

NOTES:
Installing upf.

The release is named upf-app.

To use the helm release:

  $ helm status upf-app
  $ helm get all upf-app
