# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

apiVersion: v1
kind: Pod
metadata:
  name: 5g-upf-vpp
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-openness
spec:
  nodeName: {{ .Values.node.name }}
  containers:
    - name: {{ .Release.Name }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      securityContext:
        allowPrivilegeEscalation: {{ .Values.allowPrivilegeEscalation }}
        privileged: {{ .Values.isPrivileged }}
      command: ["/bin/bash", "-c", "--"]
      args:
      - |
        while true ; do
          sleep 90000000
        done
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      volumeMounts:
        - name: hugepages
          mountPath: /hugepages
        - name: class
          mountPath: /sys/devices
          readOnly: false
        - name: upf-vol
          mountPath: /root/upf
          readOnly: false
        - name: sysfs
          mountPath: /sys
          readOnly: false
        - name: host-proc
          mountPath: /host/proc
        - name: varvol
          mountPath: /var/run
          readOnly: false
      resources:
        requests:
          {{ .Values.hugePageSize }}: {{ .Values.hugePageAmount }}
          memory: {{ .Values.memory }}
          intel.com/intel_sriov_dpdk: "1"
        limits:
           {{ .Values.hugePageSize }}: {{ .Values.hugePageAmount }}
          memory: {{ .Values.memory }}
          intel.com/intel_sriov_dpdk: "1"
  volumes:
  - name: hugepages
    emptyDir:
      medium: HugePages
  - name: class
    hostPath:
      path: /sys/devices
  - name: sysfs
    hostPath:
        path: /sys
  - name: upf-vol
    hostPath:
      path: {{ .Values.node.name }}
  - name: host-proc
    hostPath:
        path: /proc
  - name: varvol
    hostPath:
        path: /var/run

  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
