# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Actian Corporation

replicaCount: 1

image:
  name: actianzen
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

serviceType: NodePort

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
